server:
  port: 8181
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

spring:
  config:
    import:
      - classpath:/app/jwt/jwt.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/wanted?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}

  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update # `validation` or `none`

  flyway:
    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:/db/migration # ???

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html
